import type { Metadata } from 'next';
import { Vazirmatn, Noto_Nastaliq_Urdu, Amiri_Quran } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/layout/Navbar';
import { vazirmatn } from './fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang="fa" dir="rtl" className={`${vazirmatn.className} antialiased`}>
      <body className="bg-[#F8F7F3]">
        <Navbar className="absolute inset-x-0 top-0 z-10" />

        {children}
      </body>
    </html>
  );
}
